### ISSUE TITLE
Failing to parse this own type (or whatever this is)

### ISSUE THREAD

**Issue by Milvan** [considerate/go-search#8]
func getNumberOfFilesInDir(path string)(count int){
Elasticsearch DEBUG: 2017-04-22T11:33:52Z
  starting request {
    "method": "POST",
    "path": "/gosearch/function/20",
    "body": {
      "name": "getNumberOfFilesInDir",
      "parameters": [
        [
          "path",
          "string"
        ]
      ],
      "type": [
        [
          "count",
          "int"
        ]
      ]
    },
    "query": {}
  }
  

{ name: 'getNumberOfFilesInDir',
  parameters: List [ List [ "path", "string" ] ],
  type: List [ List [ "count", "int" ] ] }

/Users/marcus/dev/go-search/Tokenizer.js:129
        throw new Error('Expected '+ typeName);
        ^

Error: Expected identifier
    at expect (/Users/marcus/dev/go-search/Tokenizer.js:129:15)
    at parseTokens (/Users/marcus/dev/go-search/Tokenizer.js:152:5)
    at /Users/marcus/dev/go-search/Tokenizer.js:233:44
    at Array.forEach (native)
    at Interface.<anonymous> (/Users/marcus/dev/go-search/Tokenizer.js:225:39)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:230:10)
    at Interface.<anonymous> (readline.js:367:12)
    at Array.forEach (native)

**Comment by Milvan** [comment]
You solved this issue today right @considerate ?
